apiVersion: v1
kind: ReplicationController
metadata:
  name: ponnam-rc
spec:
  replicas: 2
  app: capgemini
template:
  metadata:
    labels:
      app: capgemini
  spec:
    containers:
    - name: capgemini-pod
      image: iponnam/cgemini:latest
      ports:
      -containerPort: 8080












